---
#
# Add flavors to OpenStack Cloud
#

# Ignore errors here incase the flavors already exist.
- name: Add flavors to overcloud
  shell: . {{ overcloudrc }}; openstack flavor create --ram {{item.memory}} --disk {{item.disk}} --vcpus {{item.cpu}} {{item.name}}
  with_items: "{{browbeat_flavors}}"
  ignore_errors: true
