---
#
# For podman containers change "container_cli" configuration to podman
#

- hosts: Stockpile
  tasks:
    - name: setting facts needed
      set_fact:
        md_output_path: "{{ browbeat_path }}/metadata/machine_facts.json"
        stockpile_user: "{{ browbeat_user }}"

- hosts: overcloud
  tasks:
    - name: setting facts
      set_fact:
        overcloud_user: "{{ host_remote_user }}"

- hosts: Undercloud
  tasks:
    - name: setting facts
      set_fact:
        undercloud_user: "{{ local_remote_user }}"

- import_playbook: stockpile/config/featureset001.yml
  vars:
    stockpile_output_path: "{{ md_output_path }}"

- hosts: Stockpile
  tasks:
    - name: run prescribe
      command: '"{{ ansible_python.executable }}" {{ browbeat_path }}/browbeat/prescribe.py {{ browbeat_path }}/metadata'

