---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: mixed-line-ending
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
  - repo: https://github.com/ansible/ansible-lint
    rev: v4.3.5
    hooks:
      - id: ansible-lint
        files:  'ansible/.(yaml|yml)$'
        exclude: ^(rally/|\.zuul\.yml)
        entry: ansible-lint --force-color -v
        additional_dependencies:
        - rich<11.0.0
