---
- project:
    templates:
      - docs-on-readthedocs
      - openstack-python37-jobs
      - openstack-tox-molecule
    vars:
      rtd_webhook_id: '51626'
    check:
      jobs:
        - openstack-tox-linters
        - openstack-tox-molecule
    gate:
      jobs:
        - openstack-tox-linters
        - openstack-tox-molecule
    post:
      jobs:
        - browbeat-upload-git-mirror

- job:
    name: browbeat-upload-git-mirror
    parent: upload-git-mirror
    description: Mirrors https://opendev.org/x/browbeat to cloud-bulldozer/browbeat
    vars:
      git_mirror_repository: cloud-bulldozer/browbeat
    secrets:
      - name: git_mirror_credentials
        secret: cloud_bulldozer_github_creds
        pass-to-parent: true

- secret:
    name: cloud_bulldozer_github_creds
    data:
      user: git
      host: github.com
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
      ssh_key: !encrypted/pkcs1-oaep
        - Vdh2OwElUZ4HF7b8NhulrH0qIiRComvtknRGJmwAg5gkGkinfG0+NOafhWQxoP4M2K6iZ
          nScol8L3U2+SrUnz3q4MJNvYsewS6rZ+Y/ONLcJH3dZiFu77NpFeNfUzjMCo+fDBTCDYe
          sEaS1Q9z7nMmOA+Ak1JWtSdKzFWubIOHuIJ1N2aCZWXhgJFxJWh1GVXfILb8HI7i5a7W/
          Mpn9s6H2bW9OZMvLvu/QLgM3e2cOCfZ5vcNLvcNfTre7HrooG7ya8lE9r3ij9mjcJ6cr2
          Vcy9k8hzf25do74JxtyZiI/QHKjugv4kadkM8fDBjJEnkfamJLkva6oMfiyXBdebM/LQy
          zmWTHI4bIHQgHjGgyWpPGSMoPnutXtqFlGyojQiTLaMoYI4lP91vU0TJKqoxTE6uAejen
          wKpVTdJUJgODR40L46m3h9iWO2I/ak6D0PCXr3VmRqmRp5ZF5gjXjGjexcYc9I4cSMkZ/
          H7OpxNuJt6VPsQvWlDmAKxa7FZZyK2oypr2daHF9aI6C3CE1NcFr35JgCGZlozuSu2a/5
          8pTUG/QmE3D+RwkGiTuK/HLtZ0f1LS0d3HiX/8NlYXJz8rS3Af7l9R4a47YPWioWjlthg
          yj4+nIYvoGyFqjRmHDfADeryLVZvdQUaPLO8RXY7ct4iZnQq2caC/4Ptc7esP4=
        - 49Lx7k4CBvq6UJOahKHShyM+C9uIYroLGhH9F5U8bGK6TGFhn6ZQs6BOBRvdZloNtgvAR
          9zVq4qFzzi1sPivxQYqZd84apZhM3pkQtOZNxQ9NL5KtpLuA6HcePaOtr0eCpHLOQUb8C
          7SPLH3vmVr1nfQR8vHRtqrBGt0hcw6NdQzUHhhBinvWYNhGtsYK9oo46IrunzHUgNbd3y
          K6Iq/uQaLJeBTX0vrI5ma+d3IsTQcx/ol/z0vslRLs6VI+vFLHnrjp6L0eWMnj+JlTjlj
          5i2UFpQ8MbtSERnGoPzqokWU78DAVWhSr0H/S6v+8sSVCiXVr3orCvRGzaQ5hrnjVU1v3
          aSOPi9WmtDeScQbeAbvMpzB89tFqLrzeU16B6kDVpxui/zUqBo1fYvhfoBQIAYwnMf+PM
          VOtZyC3/lPu9yUkJdOxbGQzuSLua5DpdMnUQ500wJQoGwotA/+gH/7AJ3mVJG1WwZcu6I
          r6Gd5aq61618Qey0vxBAVcgP4tC6XAjt0ffb6KcqJONR1mhyzFNcpwWUXmn12NO/jyiTX
          KW7RccNqBW6Z3rz3yEVsuaEwWHvhig718/k5X6/yOTeDsVUvRZ6MHDkiqgIFrdsyMiIt7
          mcSFaJ1b9ZL2WptZPTGYRRCJAevIWMoj34oE0d8dytCcoXVCvLAy/mDBzsQMUY=
        - i3Au4HhRG+wI7lVSVxWlwbGDLJpTa1rO8AVzE0548T41Bx0I1bY7gML5JRzP90pBtBt39
          7bB42tjlzjIqAj4cfCoThaspCjEYdkzRhumDcnJHCDh6yrqy0cdtqGBMbxQhllPcMiiWD
          f7HE+BPphceTYH432uKDJDRPw040mkdniDeeTi/VnRE+gq7AXPhjU0mhLn/LxtmXSrSwG
          AsQhvleavatRN99KLAkv941NlVJu8CI0UYpGgQjmBEtpo8BHDWxxR4YOoyNizANzrIBlK
          A63g51Fj65RXaT12IJ7qOkbpzE389m5Vf4Z6wBOyNxKm0ET2bpOugq/vWnv89kD2nbreN
          dawcFLkKhRtIXUKtZql2lqaUyuOLegdkU4CBqmWurjNpPxm64UT7t/LyVT6lNLp7d6mFt
          bN/3E/1ky3MCy/dSZ3kVYvP/IzJw04Z+33nnykBuyVkhG0GbRDYiVFo+/0jLqFKcjmAgn
          PcQKVV2wI6d510HFK+X5TpoRX/H/maOm5Y88OzhpzByvjPwi19P3x1gIGdKQxdb32rMCw
          5GLxy9Lerb42nMb7zGsnfvf5PAIZh17emTGQM6maRgkSUuRlyqGVCG7/xcvWo6UAUxg07
          rlNrjL+qK6y8qqqgK4VhPRVbyV6U2/Sd4GdD7Zn/O5PfFEc4Qz+x1zlr1LS3Ok=
        - jKiKcQKoY4gyzWeDAiNg5VR6DMdNglKD7I0EAErHjvqlYEaCLs7OZBYDx/UpWdhDjf5/I
          dY/0EQzXqmEQSVbAW0ig3GhR6DmMqBUyolpSlSUU/MMsITRZ178swj/MOcmHZxIL2/ad4
          XZeWA/0ypGGOXcydUHm5PeifNQQwVBhN9xwD7CcgyF0o1xBHPk0P5QCugkoeaq+ZOduQ8
          Li0GLq+1rKS6ut7mIvH5rl1z5iWVNlXhh+sXp3Xlq6jGgpTAqkaweC6w+8laCDO+qLc0t
          eGLwjfdwyAmC3AmYTVpoOilvFkvsLJ2vv6JzJV7jMjTYIuzuId2EdBZCe3lsINh7aOvI2
          8twJzJ8MghBnljoVhlpjQfWjCac/Mh4Z55l6JJNpNix6leIdq0VN8++7f5V90L1d/GxTo
          vBzDaCdZzPfCmJwOt0L2+HB5nDRcgmlR7hscPZQeztNKMQUMSLklmb07cN6Be/KOsM1Jp
          e+LYK8tR7Ye0yPiomVX4b9p0fYufFnxFvfDt+kxXS8S6Bx3lNuNOfQRB+O5KPyXNnPsOf
          +V3XydDB738sHeq6vsDvNNtbdqcKEIqBQT2GLeGMvw7Itik6joOn8rFdbLXgjOalxqR0t
          270MlJJmWbT/dm1bVUK/6BzNTKbgiKDkCa74v86qPZK7tza7BxFPbc//3V8DVc=
        - muNQ+ZEjCaeILHg2+XNsSwLgAjX3o4o3qExKm773ola0OMPKkExzVM3woYm1synPyEk1t
          EigmAM7ES5SS5IBcCUeZEZguLvpX0u22/E4vu2XckJTnTi90QV6eCsp+cp3N95e3mV3Cu
          kOhXnH6FgxAWRLz5MLfbH1iymtz4Jq9KVMp69zUBw9ab9OGFAkLZV40dCKKKbBCkfJfLU
          NVeIPmRPWRqS0dQRoPz7wmpVQRpg5+HIkaq0KyaqSmXtfRoJEIMpoKzfEMsGg/PZQym4S
          Yi3/JRi6/pXrT0XeliTWDos8D6l7wHkHXBqDkmtwXfMF2/OS2bTODxrn4DQx4DZvMFQ5a
          iTrRp/Og2nK+CwAeLOUb/KERPH2Ii92K5P9pKiCBB53jwirt7EZaw3tdx53JxgIQczcrX
          0fFAl4qE5yFtL4mEXR9vdsI3ZDfLswdPOi21bO/jBdehym/iuXCPDnDDrNID4Tf0Qrwke
          LgbmYM3iipYqv+OLQxiREOYSwSyaNtwItQYFjC32qNQYlRp5YP1F6SnprG5i1RjzpEy7r
          BBMnEBDyeHdu2sD1MQMiVOmR3MCFYY9FvVmK/PorTXLj4PPaRdMk56cnF0T2WwMLMLhXu
          ZRAkD3KSRBKFBaFSEKI1xT9Wiy6a0mNH+NgLBhHmLtBmE1w8nbHb158MlfU4Jg=
        - SQlqUgz6fkJOiAfjookJJtwXeypb2B6JU8R7DBXtbZ4txAXm5LScM4nqchOlfnqHWrLqP
          V+SXnOUJus4iSBvc2MCT/n8drOFmwxnvbP2EJTkICGeMa9KkTJVsgIl92oa7ryY1+z25G
          wmqJXx+exXaRKJAcQ4ToUmsEZCwdaFh0PQGa/U3JvqqeIxlTv+JiifdB9J0ZIEwNSJ2ay
          G0g3aqXc+3Inb+lLi5oskiDZ3NyrQPvFBkq5hO5FbfLT4irKbOuJK+0f8GOKUuMUo+9oS
          B1clsxZpjGy3tmrFGXl55RKNxRm+oPZh5SHUrs7UIF5ZFpbaMH1j7NRTPJ/0Jbb03I0Rh
          azSd5b6CXlTrKOdobPcajKLNLjqB1PYG8DWVUSslxfngX71BsT+ENUN/iawSlkpnFFMCj
          V8dSeDjJdaNSr4r2fNR4LE6gZH82FbFeuHo9Uk1wl8jhrfEOE7pV6bvnjN0jg1ctI5MMW
          QRxQNDJiOaGtk0VO/0HwVsvbXgJtvW80rTLbl/CskslZdvPsEphqA932mTYKewKmyTFvy
          MNpejGykxrbZ78irjZoPcU2hBQ6DzT36iWjrVCwTeiA596xowemr+s7SEBN74Rf1g0Uf3
          J+KO0awoxmsU1AxGh25/OQ7e6+UP7jCmn5XvbAU9g9RDitlqNC0cyPAzjnDh4E=
        - C6YM9L9kwjGOJ0wjdsOTwKrPz+tPNvRTJRgUzYpd/tHQguotIh2LcaGBMZIBpe8WSPMzo
          YItVF1itikdo9zu8Bm4yaotLwGXOkKAwb/d0vkvWGs0HcrozBmNf5v94rD/09ecuKeGjy
          Wf57XUppYtL9zEWf3vWpskrIPfYa9/iKvKpLG/iDh4YSfj236DpdyUBANP7E3ygdAg1QA
          RkS1jzqBEQLS+aJnBX7yY52YHOUnhY81WTenCs5CvHgtnZYgw7H2a6gimVvBKuuQsAxqS
          NC2uN5lqScSZHnED41+MaKfpENo5bzFQXCriFXSS6oAptAm2D5MJlLTq0Go6Z9e66yDuW
          og7BtERrZpRSvmxjZnLXBvyo9MN5CTgK2I77Roy1JooFmHXrLnq5Njz3OcuDftxo2AjsU
          SwSq6HpzhkF3vkvBPGfraQDZcSXS5WeFchJDGhapLX7Qzvuoe4CRR/aQlCWIvUyPhFi1/
          Rs4hq45ohUO+bkCYr9g5LABruOwS4XumuuUH7flKYXOXi/9hSN8SRS5aWbbQaQQVy+CvU
          5ROqzj2RA3rIjUhby9bsEw9XuUopptpxBI7GzOYX0BTX1zcznZg2Qf1GeFqUBfmFcdbWW
          0Gst/rVuG+erKVkMpWRxS9Q3Tz0nrA58Pi2jcF+q/QKzfLzA0rg5k9awZIbwfU=
        - zCtpUa8dIdA4J2HQNYVDZOsvsmf+vhkj4wCKXBGMEZoSH5xJVtM8yrVo1ZplpjK+yBVcF
          7gIbyuawT1qVMK9AkvdNWoLbAf8m3cE4lfaY8Kvw9Hc2r1bebPG/CaPA0q6bbdpTqpNta
          KrliBq5Urio2Gq/LQchy6qar9v9NbO+Utf77oYHG66O14lX+GYe05UUkc+gTiOHVFrGda
          JSFolHscPp5mqsMD6U2pZ+W3DcgBcKjs6LkRoLCoiDB9z5MikKnfl258f3HqiD7bS8yez
          K+i+cCdvAIXSEnRyRqM4oQBwxz1RDFNOfovvwYqYNXKbPOmkAIvYEatISYilYgBv0qniM
          MSg+IVUBqr85Ot0Xw6B+1fG1SSLwweE8ZpcZDF8t81nSa1ERuK3GciF6lnR2nOPHOg7/v
          aW5NBhJLMTaUXMm4uT62kR0llVk67D0N9Nwxew9EITErYVekW6WQuSO8nR1rdZd8GOW7f
          tqdXiQof1zGf/FaBlFGaZnNn/qTRQ8OrTrAPWH1HUDAX+jVwiOIGvz4NNwennCCE1hOR1
          oz1FtZqzuL25x1gQrKZ2lJcbiqcvwBrJpBRJ7kY3EE6hYO+bLho1EbQNeiupCBdxOY/Oe
          VfDBf43Tzxa1yyGanj+m2xXjtwD4pQQwjl9DI+UP7YbI9Z9434H7snRzgta8T8=


