---
- project:
    templates:
      - docs-on-readthedocs
      - openstack-tox-molecule
    vars:
      rtd_webhook_id: '51626'
    check:
      jobs:
        - openstack-tox-linters
        - openstack-tox-molecule
        - openstack-tox-py38
        - openstack-tox-py39
    gate:
      jobs:
        - openstack-tox-linters
        - openstack-tox-molecule
        - openstack-tox-py38
        - openstack-tox-py39
    post:
      jobs:
        - browbeat-upload-git-mirror

- job:
    name: browbeat-upload-git-mirror
    parent: upload-git-mirror
    description: Mirrors https://opendev.org/x/browbeat to cloud-bulldozer/browbeat
    vars:
      git_mirror_repository: cloud-bulldozer/browbeat
    secrets:
      - name: git_mirror_credentials
        secret: cloud_bulldozer_github_creds
        pass-to-parent: true

- secret:
    name: cloud_bulldozer_github_creds
    data:
      user: git
      host: github.com
      host_key: github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
      ssh_key: !encrypted/pkcs1-oaep
        - Tv3nvWzd5fMzj3v26j2RGX+TYkn71OA92TQIw6sDGmukzXxnjKTMoMuN3AwUhsJwZga/c
          pzrLfSJchCki9k+xrKPO48fdgFo9vYfWig8W72zWTWmxMa4joF3SpxISKzqkiByqpsZcX
          4ufDnvIaEdad0MZWQ0GMszEJ7bJ/XydeVshk6dgKHEa2ine0XsrUgOG6TcZwAHNz6e36w
          rryI7+PooCaTjIQxrJB7axl+uE+ng40W/JKYJJb/gYIcph8Ryb1B42T8ELzaP1/qmpAR+
          9RNhifiX4OUzxVqX3fbFoz+VbH9mI/iNdRA6/AG7Ev9EKrRuUtd8BxSgA22JMmhvWyxJo
          Fbhzr1CpAUftW46/spxwVoPjryjVfdLCI9P84QY8AiH4aXeKv5aHnyp/9VVYBQpaqDn2y
          4EnB7Uf7i8vnbA7H0rLD2YtBk2rqV2atc+n7AJ8uuH83kw1rlvMtUxVtocYiKjav0Nx9o
          fkYvw+wIhxrFE49cXofyDyWz4kW33ah0A83bmrHNIIy2+xRwHODJGsuLH/+olZnFGz6a9
          kWVtgtIsJ7mggw1EiBJKyadxk7l+7FvwaafIDXAKojSlG/Zq3cDzvwajx7hxm0wZpUFm+
          QyhQBVxfD9bfXrw/XuPk5kmLQ9Qqw3YABzG0EUeZoTuvf0zSpIk7yxJyIh6Dow=
