---
- project:
    templates:
      - docs-on-readthedocs
      - openstack-python37-jobs
      - openstack-tox-molecule
    vars:
      rtd_webhook_id: '51626'
    check:
      jobs:
        - openstack-tox-linters
        - openstack-tox-molecule
    gate:
      jobs:
        - openstack-tox-linters
        - openstack-tox-molecule
    post:
      jobs:
        - browbeat-upload-git-mirror

- job:
    name: browbeat-upload-git-mirror
    parent: upload-git-mirror
    description: Mirrors https://opendev.org/x/browbeat to cloud-bulldozer/browbeat
    vars:
      git_mirror_repository: cloud-bulldozer/browbeat
    secrets:
      - name: git_mirror_credentials
        secret: cloud_bulldozer_github_creds
        pass-to-parent: true

- secret:
    name: cloud_bulldozer_github_creds
    data:
      user: git
      host: github.com
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
      ssh_key: !encrypted/pkcs1-oaep
        - Nq0/3wUmsqt7oEmISlDeAxuk1aw+xO6lxNZc0lMuwWPV0xlyH0cuZMZY6olIxQr+ZNVhK
          PmoYzD+JMpIok+dyv/NS95eqiwHGy3uGxK88rNoAh6A33e/f+DA//L7+cZiX/cb5lFjFv
          cQFllYWOh8WOpXQpNZD91sMF6pdtI41cgCtn6chljpiOJ04648N1HqhK+qe8+6OfuEGKs
          pXdHO/E2Nz4NOHY5JgKRgCHZihC58uEP31607OOA8gdbsijCzqOct8n48CJQHYbkdqCwM
          moos0V/A1suUlmoUIL7KBeXLLM1HhaC9DkGmo2o9i5fFegGilC3pJG1Bdi2eKqQShs9ic
          OKOhhYPcGEVuHRfnN2zOaTiep32DHbcNwNlYgiqe4zfufrXrtYichmbMKkoyWEK6LNwn8
          5xhHDDwHYOYd0uERzi6Qq5TDqzEjJVxPnycYupR4FzL1bIZJGUiiGiYMtntWEzyVWaTf0
          a+ayjqD0qAcaVp/DEzlTZRCJOX5QKwjMuZosmY6f2hAcXl6NpML5GWJ5teKUcOyb1UcLW
          RP9760qPOz047fc4Hjt3dcdsjylnUpJJJG+s9ORYcibGyA6BeRwFmnxlH5QMv4CI4Q2oK
          ZTmTAtyD6JSk1VqEzupnHzEbNv04z/YUoKhPQBo55B1i/L1j27usXwmAkro/sE=
        - qEQu5BhgVdNacJQhcfqRXObLeNPiscL+uou5QyPIlPWDcHAjwvdAP9lKM5KkzVm2HBBd6
          +jIZPmYnBRg507JFUI7H3cJ+sFEz5buM+E7NsxvLvoqCU0akYt4yhhkBXoHUAY2Cbbccp
          TAGmu7outW1+IJqd7YN89nQb4z6RKHmhv4uiOClbNqf7gVepTVg37OtL5uVLx5pLgCQ93
          cd7UZMFO69l/GdqT5h345ZKdOungLbCwt6p/72teMKE/XzYAEd+EXF/aINWF6+2xozDDI
          U7ohGQ4YDDUj7xPcfI/dXYRr+MRHiEEs27rOhRYYfkrhHuFmU0X3z6b4sUCEwJiO+3ugc
          /QrDq0r3VAEsTqpYEkgQWlZhDsbzc6FMvvy2xcMHueS+Oces2Wgu1eFTNFF8371h4vzg2
          7w0InAGYn+kpm64NjsACKFRAsRfPQmkXuu4Fob+PRliV9dgKVxU0HsAhysIaGgRLyCpOm
          yE3bdOrZqQByJtmA+pFhV3g2bdTgp1oaVxRBbh5FE9EZfE1qvgnvT/lDlTbHhlb+7dKSj
          ND26nkxI5bKX4Zzl+1sxmo90Grgn0LC+K7erD/09OKEXwPre3ed4vjTus29kXIgYfNP/z
          2/exNhhednwDKKp1yT/qCs43LWgsLgZl4blml9YML4mjEjpg9rHbM5iNpsSlSg=
        - u4pZaKuU9xJ0OxgOVB2gS2ssCBCekg1/TTAVozU7RLQvbB7Rzvx25PrmyybH7SN4ZOrxd
          +G+n66yXDWuF4hFyqZOuyIiOdrYp9kaN2bz8nZ/ZrOHJ5kV+V38EV+xeNkP8rqUW1uiR9
          vTTXErSyVyq7fO47m0ksHQoGCxyqfVjKNhZNlSPADTC9/e0RpFRNtbC5tGXZO/P+D8P/T
          rOdamfEXD7Ip6jB8RAUtS1I9Me69RXXOIyOR0rfTim3rO1JIGX8LAvgFePUqM1dIbo92E
          oU/k+e28RT18QXodTKccDLjTKiMLJ9fNfF++mxLQF+RBdqEPBkCsP8iPNTP9EopRhOhtd
          T7BugPNtznQNk0iF7kvLfQ+/HlXa7e50g/tBh/dv+Ckj6hfBTT0kVh+nhT/BlTm/Sc0fa
          GZFRU0Dk7mdRtUTvs9FT9NuKtlv0uyDgA0AEX1w21iM7Ir+nTpuD9TDkLc2AltV5ALRwU
          SatT1pK58gGvf56bx9GQZa86myi268ck5/kmzXtdGaQdkvFYbrnf9BQkAAIMhkLQO3CX9
          ceoWky+Jj7Irm2bSyoWDbwqUuKMBPnrvx/g8JvjKJTQBIl2q82SXJSXOFZqSvgsQjyO2V
          G9r+h69FkGrekjkBFFcUm8J1OJRB0n8L2SLAFPXdpoUOovlo+qakhFgVc7d3/w=
        - oKRnzXLA4alTmlvc3Oo/QQWjweUZDnpBQWIov107bK1gw5/iBMdEBKtj90C1VIOpV7dWB
          ljfxK39v3kcqlI6s/hJ+sXeBngox2I82OnANsuK9rEdC/PNBxolgnHjWJlYC8DcWFcicS
          J2k74qo//Txd5ob+CRn67v2FYb6VsHLHr9ZfjN0+YLLjAfVGU5grKLaq5hjy4TFK3lk6B
          miFoxwNrfTl5AgcQZTIyw5+LU9Bnr4TDGYHjTASgcrg39J9OLPdwtZ31k5lVTAZJT10nF
          74xoM2ne2wxgyBR1C69k8Hea1AWIny4jqE1KsZDELqUICEu8nwH7Una7hZQzJMyO3uPq2
          DsEmRjatKblfAfGeLo1nhGR4Q/4OSwsd9RldriLNX43BpnHZYtLJIl2AE0+pAaijBTqsh
          Py4BQ6X5D5K1Fe1cbeLjp0aHZd7s/fdox76vNv9N5lHSTbhGgD8AIpBNBFRw4nyonppH5
          goQEnQ8AiKCEaELWtKx2XPiYSjydoySiy3ZQYC4qXxfpccZO1ST4bsSRnt40Sav7tY9TJ
          LVe/d6oQgfnmPK6LP3U5EwjsXiCkom6UbwWmIutSwE9tOvkyuLg/xmSMuHwv24LQrMnTq
          WO1yhOuomQbTiBm9dDOR3xdcbIA/0Y4ThlZfzWX53lXVtgxIdLXqVsrW87Y3cg=
        - xk9arzO2O9I/pca26vp+InlnDAkd/3mgN6voDvPsWKulR0/88uzX6gHZLwgyniS2qC7RU
          Q21/Vlcty8oSXJJeSn9AwBg1kWfIh+ke3bBUAIlhT8WupMck/cr3Thoz1Q0WqMekt0mWL
          K8+a2laj+aIs65EYx8eOUXbMVE58l1QDmbFfv5lft/pGjzDt+nWWseoqtBhx2iJ0QIbr1
          IrE544L5nkeMEC1EKHuTWRcIspE41FxFVyYV3v4E/7M1dCMidgaGzpcC7aCjO0OxeEA4f
          wj7cTQuuT8cPN1fQmifVB6WzJ7kvbJRovp4ecu5nmH93yqNADKgDjd8a2fHtxZLitFmMI
          UeIYvZG/MeRV4my37yS1vdQ7sdMjtKKxfIKchleNiljDs+o+6D5RltOx7XACcnd87uw40
          HQ4X95bzItaBOSV+U8qG+QvRk1AiCobJfYwJwqZsqJZCHgCkaVzVTzUSYyLUHttfJf8Vo
          jq/WVKwAp5qpOz8irRUE73mA60u63/xzEnPhlhvV2AOhIWXhxKfVqaaexDGLmVyumte59
          qznlj2tFNu3jUveVGC9nPbtQP4PUV/QACWL4eRGQMf0GkN2yXyAy2Zcala3Jcq/EbmrIh
          chvdwqMwEliW8HZn8L69q+ITcvhFotnrNDMaMqMJFlkKt2mjfQOM6kdzVc1YCM=
        - tJ47PNqXypCvl2z7h2LEt5FM2Lsk8eGlHr+xzAayPywP55qr/itoLET4oAShhOm018DLE
          zuizO7szzDBSV3Wy/7LyYn6k3g6zWp1y/akDojEKr8qmtgz52K5baQ2LOxdZD/5UloMhv
          BOHBjVAlPfZ9/Nx4UZgZ6m9nYD/1ZOXw0SPaozveRJhIpkabO2ZNjmTty73mEP40onKog
          EqLVX6H9yOzi4vg/2zeZoFnIEvDlBICru37KBYoC8cgjgl3R7dNk6nAExFWZL+GP2NFan
          Tm0uYoaJpmrYQMqEmiwiAy7zgpZtcXM7rnjdH9LSzJuHJDhx5totxopNQJLVeqEB5fDlO
          428ofKIzKm9TMF5/iSZYKf1jlReUKSu5koAtChXbZQPWuR3QySvIhnXoIT3IR+01xDE2N
          8ASyg2PA67dA1714v+n0Fue9aGa2ZkHVyzshvnYFu7+2iQyRQUNpWD8zJT1cdecHO/pjN
          ro3W6cw+RSHgBalsxz+EYM0KNIjoCIIKYhpr77UDk0Iy5ahP/rf9DpbaQ8qhBRH6Jyont
          cpblQpy8jJTKzE3DtW9sq4uDNbfiNO7T7j4ULuMhOoFS7FEXHmd2AiWd3SJuz6EOZWPJY
          JElz14G+lQV8jCb5zb0NHrAdPgscLk7gQ5f1HaIjK11WZU6Xylyig6xU7xWjmM=
