# Complete set of Stress Tests, this can take a long time (day(s))
browbeat:
  cloud_name: openstack
  rerun: 3
  rerun_type: iteration
  # This option enables starting collectd before running workloads,
  # and stopping collectd after running workloads. It should be enabled
  # when it is required to store collectd data only when workloads
  # are running. Please install collectd by running the command
  # "cd ansible;ansible-playbook -i hosts.yml -vvv install/collectd.yml" before
  # setting this option to true.
  start_stop_collectd: false
  create_grafana_annotations: false
ansible:
  hosts: ansible/hosts
  metadata_playbook: ansible/gather/stockpile.yml
  logging_playbook: ansible/common_logging/browbeat_logging.yml
  start_collectd_playbook: ansible/install/start-collectd.yml
  stop_collectd_playbook: ansible/install/stop-collectd.yml
  check_collectd_config_playbook: ansible/install/check-collectd-config.yml
  ssh_config: ansible/ssh-config
elasticsearch:
  enabled: true
  host: 1.1.1.1
  port: 9200
  life: shortterm
  regather: true
  metadata_files:
    - name: hardware-metadata
      file: metadata/hardware-metadata.json
    - name: environment-metadata
      file: metadata/environment-metadata.json
    - name: software-metadata
      file: metadata/software-metadata.json
    - name: version
      file: metadata/version.json
grafana:
  enabled: true
  host: example.grafana.com
  port: 3000
  dashboards:
    - openstack-general-system-performance
filebeat:
  enabled: false
rally:
  sleep_before: 5
  sleep_after: 5
  plugins:
    - glance: rally/rally-plugins/glance
    - neutron: rally/rally-plugins/neutron
    - netcreate-boot: rally/rally-plugins/netcreate-boot
    - cinder: rally/rally-plugins/cinder
    - workloads: rally/rally-plugins/workloads
shaker:
  server: 1.1.1.1
  port: 5555
  flavor: m1.small
  join_timeout: 600
  sleep_before: 5
  sleep_after: 5
  shaker_region: regionOne
  external_host: 2.2.2.2

workloads:
# Rally
  - name: authenticate
    enabled: true
    type: rally
    rally_deployment: overcloud
    concurrency:
      - 64
      - 128
      - 192
      - 256
      - 320
      - 384
      - 448
      - 512
    times: 10000
    scenarios:
      - name: authentic-keystone
        enabled: true
        file: rally/authenticate/keystone-cc.yml
        sla_max_avg_duration: 6
        sla_max_seconds: 30
        sla_max_failure: 0
      - name: authentic-neutron
        enabled: true
        file: rally/authenticate/validate_neutron-cc.yml
        sla_max_avg_duration: 18
        sla_max_seconds: 30
        sla_max_failure: 0
      - name: authentic-nova
        enabled: true
        file: rally/authenticate/validate_nova-cc.yml
        sla_max_avg_duration: 12
        sla_max_seconds: 30
        sla_max_failure: 0
  - name: cinder
    enabled: true
    type: rally
    rally_deployment: overcloud
    concurrency:
      - 16
      - 32
      - 48
      - 64
    times: 128
    scenarios:
      - name: create-attach-volume-centos
        enabled: true
        file: rally/cinder/cinder-create-and-attach-volume-cc.yml
        sla_max_seconds: 30
        sla_max_failure: 0
      - name: create-attach-volume-cirros
        enabled: true
        image_name: cirro5
        file: rally/cinder/cinder-create-and-attach-volume-cc.yml
        flavor_name: m1.tiny
        sla_max_seconds: 30
        sla_max_failure: 0

      - name: create-and-list-snapshots
        enabled: true
        size: 1
        file: rally/cinder/cinder-create-and-list-snapshots.yml
        sla_max_seconds: 30
        sla_max_failure: 0

      - name: create-and-list-volume
        enabled: true
        size: 1
        file: rally/cinder/cinder-create-and-list-volume.yml
        sla_max_seconds: 30
        sla_max_failure: 0

      - name: create-and-update-volume
        enabled: true
        size: 1
        file: rally/cinder/cinder-create-and-update-volume.yml
        sla_max_seconds: 30
        sla_max_failure: 0

  - name: keystonebasic
    enabled: true
    type: rally
    rally_deployment: overcloud
    concurrency:
      - 256
    times: 5000
    scenarios:
      - name: create-and-list-tenants
        enabled: true
        file: rally/keystonebasic/create_and_list_tenants-cc.yml
        sla_max_seconds: 30
        sla_max_failure: 0
      - name: create-and-list-users
        enabled: true
        file: rally/keystonebasic/create_and_list_users-cc.yml
        sla_max_seconds: 30
        sla_max_failure: 0
  - name: neutron
    enabled: true
    type: rally
    rally_deployment: overcloud
    concurrency:
      - 16
      - 32
      - 48
      - 64
    times: 500
    scenarios:
      - name: create-list-network
        enabled: true
        file: rally/neutron/neutron-create-list-network-cc.yml
        sla_max_seconds: 30
        sla_max_failure: 0
      - name: create-list-port
        enabled: true
        file: rally/neutron/neutron-create-list-port-cc.yml
        sla_max_seconds: 30
        sla_max_failure: 0
      - name: create-list-router
        enabled: true
        file: rally/neutron/neutron-create-list-router-cc.yml
        sla_max_seconds: 30
        sla_max_failure: 0
      - name: create-list-security-group
        enabled: true
        file: rally/neutron/neutron-create-list-security-group-cc.yml
        sla_max_seconds: 30
        sla_max_failure: 0
      - name: create-list-subnet
        enabled: true
        file: rally/neutron/neutron-create-list-subnet-cc.yml
        sla_max_seconds: 30
        sla_max_failure: 0
  - name: nova
    enabled: true
    type: rally
    rally_deployment: overcloud
    concurrency:
      - 16
      - 32
      - 48
      - 64
      - 80
      - 96
    times: 128
    scenarios:
      - name: boot-snapshot-delete-cirros
        enabled: true
        file: rally/nova/nova-boot-snapshot-cc.yml
        image_name: cirro5
        flavor_name: m1.xtiny
      - name: boot-list-cirros
        enabled: true
        image_name: cirro5
        file: rally/nova/nova-boot-list-cc.yml
        flavor_name: m1.xtiny
      - name: boot-show-cirros
        enabled: true
        image_name: cirro5
        file: rally/nova/nova-boot-show-cc.yml
        flavor_name: m1.xtiny
      - name: boot-bounce-delete-cirros
        enabled: true
        image_name: cirro5
        file: rally/nova/nova-boot-bounce-delete-cc.yml
        flavor_name: m1.xtiny
      - name: boot-lock-unlock-cirros
        enabled: true
        image_name: cirro5
        file: rally/nova/nova-lock-unlock-cc.yml
        flavor_name: m1.xtiny
      - name: boot_server_from_volume_and_resize
        enabled: true
        image_name: cirro5
        file: rally/nova/nova-boot-from-volume-and-resize.yml
        initial_flavor_name: m1.tiny
        final_flavor_name: m1.small
  - name: glance
    enabled: true
    type: rally
    rally_deployment: overcloud
    concurrency:
      - 8
    times: 10
    scenarios:
      - name: create-image-boot-instances
        enabled: true
        image_location: /home/stack/cirros.qcow2
        instances: 2
        flavor_name: m1.small
        file: rally/glance/create-image-and-boot-instances-cc.yml
      - name: create-and-delete-image
        enabled: true
        image_location: /home/stack/cirros.qcow2
        flavor_name: m1.small
        file: rally/glance/create-and-delete-image-cc.yml
      - name: create-and-list-image
        enabled: true
        image_location: /home/stack/cirros.qcow2
        file: rally/glance/create-and-list-image-cc.yml
      - name: list-images
        enabled: true
        file: rally/glance/list-images-cc.yml
  - name: plugins
    enabled: true
    type: rally
    rally_deployment: overcloud
    concurrency:
      - 16
      - 32
      - 48
      - 64
    times: 128
    scenarios:
      - name: netcreate-boot
        enabled: true
        enable_dhcp: true
        image_name: cirro5
        flavor_name: m1.tiny
        file: rally/rally-plugins/netcreate-boot/netcreate_nova_boot.yml
        sla_max_avg_duration: 12
        sla_max_seconds: 30
        sla_max_failure: 0
      - name: router-subnet-create-delete
        enabled: true
        num_networks:  50
        file: rally/rally-plugins/neutron/router_subnet_create_delete.yml
      - name: glance-create-boot-delete
        enabled: true
        image_location: /home/stack/cirros.qcow2
        flavor_name: m1.xtiny
        file: rally/rally-plugins/glance/glance_create_boot_delete.yml
      - name: rally-port-create-associate
        file: rally/rally-plugins/neutron/port_create_assoicate.yml
        enabled: true
        num_networks: 1
        num_ports: 100
        hypervisor: overcloud-compute-0.localdomain
        browbeat_ssh_config: ansible/ssh-config
        username: heat-admin
      - name: create-vm-with-volume-list
        enabled: true
        image_name: centos7
        flavor_name: m1.small
        file: rally/rally-plugins/cinder/boot_vm_attach_volume_list.yml

# file for shaker should be one of https://opendev.org/performa/shaker/src/branch/master/shaker/scenarios/openstack
# Shaker scenarios require atleast 2 compute nodes
  - name: l2-4-1
    enabled: true
    type: shaker
    density: 4
    compute: 1
    progression: linear
    time: 60
    file: dense_l2.yaml
  - name:  l2-8-1
    enabled: true
    type: shaker
    density: 8
    compute: 1
    progression: linear
    time: 60
    file: dense_l2.yaml
  - name: l2-4-2
    enabled: true
    type: shaker
    density: 4
    compute: 2
    progression: linear
    time: 60
    file: dense_l2.yaml
  - name: l2-8-2
    enabled: true
    type: shaker
    density: 8
    compute: 2
    progression: linear
    time: 60
    file: dense_l2.yaml
  - name: l3-north-south-4-1
    enabled: true
    type: shaker
    placement: single_room
    density: 4
    compute: 1
    progression: null
    file: dense_l3_north_south.yaml
  - name: l3-north-south-8-1
    enabled: false
    type: shaker
    placement: single_room
    density: 8
    compute: 1
    progression: null
    time: 60
    file: dense_l3_north_south.yaml
  - name: l3-north-south-4-2
    enabled: true
    type: shaker
    placement: single_room
    density: 4
    compute: 2
    progression: null
    time: 60
    file: dense_l3_north_south.yaml
  - name: l3-north-south-8-2
    enabled: true
    type: shaker
    placement: single_room
    density: 8
    compute: 2
    progression: null
    time: 60
    file: dense_l3_north_south.yaml
  - name: l3-east-west-4-1
    enabled: true
    type: shaker
    density: 4
    compute: 1
    placement: single_room
    time: 60
    file: dense_l3_east_west.yaml
  - name: l3-east-west-8-1
    enabled: true
    type: shaker
    density: 8
    compute: 1
    placement: single_room
    time: 60
    file: dense_l3_east_west.yaml
  - name: l3-east-west-4-2
    enabled: true
    type: shaker
    density: 4
    compute: 2
    placement: single_room
    time: 60
    file: dense_l3_east_west.yaml
  - name: l3-east-west-8-2
    enabled: true
    type: shaker
    density: 8
    compute: 2
    time: 60
    placement: single_room
    file: dense_l3_east_west.yaml
