---

- name: Clone e2e-benchmarking
  git:
    repo: 'http://github.com/cloud-bulldozer/e2e-benchmarking.git'
    dest: "{{ browbeat_path }}/ansible/gather/e2e-benchmarking"
    version: master
    force: yes

- name: Deploy benchmark operator and make changes to scripts
  shell: |
    ./install_e2e_benchmarking.sh
  args:
    chdir: "{{ browbeat_path }}/ansible"
