---
- hosts: localhost
  tasks:
    - debug:
        msg: "redirecting to browbeat installation based on deployment type"

- name: Install browbeat
  import_playbook: browbeat_rhoso.yaml
  vars:
    rally_undercloud_enabled: false
  when: is_rhoso_deployment

- name: Install browbeat
  import_playbook: browbeat_rhosp.yaml
  when: not is_rhoso_deployment
