---
#
# Playbook to install Browbeat (Rally + Shaker) on undercloud
#

- hosts: Browbeat
  remote_user: "{{ browbeat_user }}"
  roles:
    - common
    - osp_version
    - browbeat
    - stockpile
    - { role: browbeat-results, when: browbeat_results_in_httpd}
    - firewall
    - rally
    - shaker
    - { role: flavors, when: browbeat_create_flavors}
    - { role: images, when: browbeat_upload_guest_images}
    - { role: workloads, when: install_browbeat_workloads}
  environment: "{{proxy_env}}"

- hosts: Controller, Compute
  remote_user: "{{ host_remote_user }}"
  roles:
    - no-sshd-dns
