---
#
# Playbook to install Browbeat(Rally) for RHOSO
#

- hosts: localhost
  gather_facts: true
  vars:
    ansible_user: "{{ browbeat_user }}"
    ansible_python_interpreter: "{{ python_interpreter }}"
  roles:
    - browbeat-rhoso-prep
    - browbeat
    - { role: browbeat-results, when: browbeat_results_in_httpd|bool}
    - firewall
    - rally
    - { role: flavors, when: browbeat_create_flavors|bool}
    - { role: images, when: browbeat_upload_guest_images|bool}
  environment: "{{proxy_env}}"
