---
#
# Generic Playbook to install collectd on generic machine types, use tags to separate machine type:
#
# Examples:
#
# ansible-playbook -i hosts install/collectd-generic.yml --tags="baremetal"
# ansible-playbook -i hosts install/collectd-generic.yml --tags="guest"
# ansible-playbook -i hosts install/collectd-generic.yml --tags="graphite"
# ansible-playbook -i hosts install/collectd-generic.yml --tags="baremetal,guest"
#

- hosts: baremetal
  remote_user: root
  vars:
    config_type: baremetal
  roles:
    - {role: epel }
    - collectd-generic
  tags: baremetal
  environment: "{{proxy_env}}"

- hosts: guest
  remote_user: root
  vars:
    config_type: guest
  roles:
    - {role: epel }
    - collectd-generic
  tags: guest
  environment: "{{proxy_env}}"

- hosts: Graphite
  remote_user: root
  vars:
    config_type: graphite
  roles:
    - {role: epel }
    - collectd-generic
  tags: graphite
  environment: "{{proxy_env}}"
