---
#
# Generic Playbook to install collectd,  use tags to separate machine type:
#
# Examples:
#
# ansible-playbook -i hosts install/collectd.yml --tags="undercloud"
# ansible-playbook -i hosts install/collectd.yml --tags="controller"
# ansible-playbook -i hosts install/collectd.yml --tags="compute"


- hosts: Undercloud
  remote_user: "{{ local_remote_user }}"
  vars:
    config_type: undercloud
  roles:
    - { role: osp_version }
    - { role: containers }
    - { role: common, when: collectd_undercloud|bool }
    - { role: collectd, when: collectd_undercloud|bool }
  tags: undercloud
  environment: "{{proxy_env}}"

- hosts: Controller
  remote_user: "{{ host_remote_user }}"
  vars:
    config_type: controller
  roles:
    - { role: osp_version }
    - { role: containers }
    - { role: common, when: collectd_controller|bool }
    - { role: collectd, when: collectd_controller|bool }
  tags: controller

- hosts: Compute
  remote_user: "{{ host_remote_user }}"
  vars:
    config_type: compute
  roles:
    - { role: osp_version }
    - { role: containers }
    - { role: common, when: collectd_compute|bool }
    - { role: collectd, when: collectd_compute|bool }
  tags: compute

- hosts: Networker
  remote_user: "{{ host_remote_user }}"
  vars:
    config_type: networker
  roles:
    - { role: osp_version }
    - { role: containers }
    - { role: common, when: collectd_networker|bool }
    - { role: collectd, when: collectd_networker|bool }
  tags: networker

- hosts: BlockStroage
  remote_user: "{{ host_remote_user }}"
  vars:
    config_type: blockstorage
  roles:
    - { role: osp_version }
    - { role: containers }
    - { role: common, when: collectd_blockstoarge|bool }
    - { role: collectd, when: collectd_blockstorage|bool }
  tags: blockstorage

- hosts: ObjectStorage
  remote_user: "{{ host_remote_user }}"
  vars:
    config_type: objectstorage
  roles:
    - { role: osp_version }
    - { role: containers }
    - { role: common, when: collectd_objectstorage|bool }
    - { role: collectd, when: collectd_objectstorage|bool }
  tags: objectstorage

- hosts: CephStorage
  remote_user: "{{ host_remote_user }}"
  vars:
    config_type: cephstorage
  roles:
    - { role: osp_version }
    - { role: containers }
    - { role: common, when: collectd_cephstorage|bool }
    - { role: collectd, when: collectd_cephstorage|bool }
  tags: cephstorage
