- hosts: localhost
  gather_facts: true
  vars:
    ansible_user: "{{ browbeat_user }}"
    ansible_python_interpreter: "{{ python_interpreter }}"
  roles:
    - { role: collectd-rhoso }
  environment: "{{proxy_env}}"

- name: trigger the cronjob to index data from OCP
  import_playbook: toggle-indexing-cron-job.yml
  vars:
    cron_state: "present"
