---
#
# Playbook to install Carbon and Graphite
#

- hosts: Graphite
  remote_user: root
  roles:
    - {role: epel, when: ansible_distribution_major_version == '7'}
    - graphite
  environment: "{{proxy_env}}"
