---
- name: set fact collectd_container
  import_playbook: pre-collectd.yml
  when: not is_rhoso_deployment

- name: Start containerized collectd (Stein and greater recommended)
  import_playbook: start-collectd-container.yml
  when: hostvars['undercloud']['collectd_container'] and not is_rhoso_deployment

- name: Start collectd installed through RPMs
  import_playbook: start-collectd-baremetal.yml
  when: not hostvars['undercloud']['collectd_container'] and not is_rhoso_deployment

- name: Start collectd on RHOSO OCP workers
  import_playbook: start-collectd-rhoso.yml
  when: is_rhoso_deployment
