- hosts: localhost
  tasks:
    - name: stop collectd on OCP nodes.
      shell: |
        oc scale -n ospperf statefulset osp-controlplane-collectd --replicas=0
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      ignore_errors: yes

- name: stop the cronjob to stop index data from OCP
  import_playbook: toggle-indexing-cron-job.yml
  vars:
    cron_state: "absent"
