# Complete set of Glance Benchmarks
browbeat:
  cloud_name: openstack
  rerun: 1
  rerun_type: iteration
  start_stop_collectd: false
  create_grafana_annotations: false
ansible:
  hosts: ansible/hosts
  metadata_playbook: ansible/gather/stockpile.yml
  logging_playbook: ansible/common_logging/browbeat_logging.yml
  start_collectd_playbook: ansible/install/start-collectd.yml
  stop_collectd_playbook: ansible/install/stop-collectd.yml
  check_collectd_config_playbook: ansible/install/check-collectd-config.yml
  ssh_config: ansible/ssh-config
elasticsearch:
  enabled: false
  host: 1.1.1.1
  port: 9200
  life: shortterm
  regather: false
  metadata_files:
    - name: hardware-metadata
      file: metadata/hardware-metadata.json
    - name: environment-metadata
      file: metadata/environment-metadata.json
    - name: software-metadata
      file: metadata/software-metadata.json
    - name: version
      file: metadata/version.json
grafana:
  enabled: true
  host: example.grafana.com
  port: 3000
  dashboards:
    - openstack-general-system-performance
filebeat:
  enabled: false
rally:
  sleep_before: 5
  sleep_after: 5
  plugins:
    - glance: rally/rally-plugins/glance
shaker:
  server: 1.1.1.1
  port: 5555
  flavor: m1.small
  join_timeout: 600
  sleep_before: 0
  sleep_after: 0
  shaker_region: regionOne
  external_host: 2.2.2.2

workloads:
  - name: glance
    enabled: true
    type: rally
    concurrency:
      - 8
    times: 10
    scenarios:
      - name: create-image-boot-instances
        enabled: true
        image_location: /home/stack/cirros.qcow2
        instances: 2
        flavor_name: m1.small
        file: rally/glance/create-image-and-boot-instances-cc.yml
      - name: create-and-delete-image
        enabled: true
        image_location: /home/stack/cirros.qcow2
        flavor_name: m1.small
        file: rally/glance/create-and-delete-image-cc.yml
      - name: create-and-list-image
        enabled: true
        image_location: /home/stack/cirros.qcow2
        file: rally/glance/create-and-list-image-cc.yml
      - name: list-images
        enabled: true
        file: rally/glance/list-images-cc.yml
