# Complete set of Gnocchi Stress tests run minimal number of times.
# Good sanity test to see if OSP will be able to handle the longer stress tests.
browbeat:
  cloud_name: openstack
  rerun: 1
  rerun_type: iteration
  start_stop_collectd: false
  create_grafana_annotations: false
ansible:
  hosts: ansible/hosts
  metadata_playbook: ansible/gather/stockpile.yml
  logging_playbook: ansible/common_logging/browbeat_logging.yml
  start_collectd_playbook: ansible/install/start-collectd.yml
  stop_collectd_playbook: ansible/install/stop-collectd.yml
  check_collectd_config_playbook: ansible/install/check-collectd-config.yml
  ssh_config: ansible/ssh-config
elasticsearch:
  enabled: false
  host: 1.1.1.1
  port: 9200
  life: shortterm
  regather: false
  metadata_files:
    - name: hardware-metadata
      file: metadata/hardware-metadata.json
    - name: environment-metadata
      file: metadata/environment-metadata.json
    - name: software-metadata
      file: metadata/software-metadata.json
    - name: version
      file: metadata/version.json
grafana:
  enabled: true
  host: example.grafana.com
  port: 3000
  dashboards:
    - openstack-general-system-performance
filebeat:
  enabled: false
rally:
  sleep_before: 5
  sleep_after: 5
  plugins:
    - gnocchi: rally/rally-plugins/gnocchi
shaker:
  server: 1.1.1.1
  port: 5555
  flavor: m1.small
  join_timeout: 600
  sleep_before: 0
  sleep_after: 0
  shaker_region: regionOne
  external_host: 2.2.2.2

workloads:
  - name: Gnocchi
    enabled: true
    type: rally
    concurrency:
      - 5
    times: 10
    scenarios:
      - name: gnocchi-archive-policy-list
        enabled: true
        file: rally/rally-plugins/gnocchi/gnocchi-archive-policy-list.yml
      - name: gnocchi-create-archive-policy
        enabled: true
        file: rally/rally-plugins/gnocchi/gnocchi-create-archive-policy.yml
      - name: gnocchi-create-delete-archive-policy
        enabled: true
        file: rally/rally-plugins/gnocchi/gnocchi-create-delete-archive-policy.yml

      - name: gnocchi-archive-policy-rule-list
        enabled: true
        file: rally/rally-plugins/gnocchi/gnocchi-archive-policy-rule-list.yml
      - name: gnocchi-create-archive-policy-rule
        enabled: true
        file: rally/rally-plugins/gnocchi/gnocchi-create-archive-policy-rule.yml
      - name: gnocchi-create-delete-archive-policy-rule
        enabled: true
        file: rally/rally-plugins/gnocchi/gnocchi-create-delete-archive-policy-rule.yml

      - name: gnocchi-capabilities-list
        enabled: true
        file: rally/rally-plugins/gnocchi/gnocchi-capabilities-list.yml

      # Aggregation has several potential scenarios due to parameterization
      - name: gnocchi-metric-aggregation-single-page
        enabled: true
        file: rally/rally-plugins/gnocchi/gnocchi-metric-aggregation.yml
      - name: gnocchi-metric-aggregation-all
        enabled: true
        all_metrics: true
        file: rally/rally-plugins/gnocchi/gnocchi-metric-aggregation.yml
      - name: gnocchi-metric-aggregation-agg-mean-refresh
        enabled: true
        all_metrics: true
        aggregation: mean
        refresh: true
        file: rally/rally-plugins/gnocchi/gnocchi-metric-aggregation.yml
      # Get Measures has several potential scenarios due to parameterization
      - name: gnocchi-metric-get-measures-single-page
        enabled: true
        file: rally/rally-plugins/gnocchi/gnocchi-metric-get-measures.yml
      - name: gnocchi-metric-get-measures-all
        enabled: true
        all_metrics: true
        file: rally/rally-plugins/gnocchi/gnocchi-metric-get-measures.yml
      - name: gnocchi-metric-get-measures-agg-mean-refresh
        enabled: true
        all_metrics: true
        aggregation: mean
        refresh: true
        file: rally/rally-plugins/gnocchi/gnocchi-metric-get-measures.yml
      # List/Create/Create&Delete Metrics
      - name: gnocchi-metric-list
        enabled: true
        file: rally/rally-plugins/gnocchi/gnocchi-metric-list.yml
      - name: gnocchi-create-metric
        enabled: true
        file: rally/rally-plugins/gnocchi/gnocchi-create-metric.yml
      - name: gnocchi-create-delete-metric
        enabled: true
        file: rally/rally-plugins/gnocchi/gnocchi-create-delete-metric.yml

      - name: gnocchi-resource-list
        enabled: true
        file: rally/rally-plugins/gnocchi/gnocchi-resource-list.yml
      - name: gnocchi-create-resource
        enabled: true
        file: rally/rally-plugins/gnocchi/gnocchi-create-resource.yml
      - name: gnocchi-create-delete-resource
        enabled: true
        file: rally/rally-plugins/gnocchi/gnocchi-create-delete-resource.yml

      - name: gnocchi-resource-type-list
        enabled: true
        file: rally/rally-plugins/gnocchi/gnocchi-resource-type-list.yml
      - name: gnocchi-create-resource-type
        enabled: true
        file: rally/rally-plugins/gnocchi/gnocchi-create-resource-type.yml
      - name: gnocchi-create-delete-resource-type
        enabled: true
        file: rally/rally-plugins/gnocchi/gnocchi-create-delete-resource-type.yml

      - name: gnocchi-status-get
        enabled: true
        file: rally/rally-plugins/gnocchi/gnocchi-status-get.yml
      - name: gnocchi-status-get-detailed
        enabled: true
        detailed: True
        file: rally/rally-plugins/gnocchi/gnocchi-status-get.yml
