# Stress test designed for telemetry services (ceilometer, gnocchi) by
# booting persisting xtiny cirros instances. It boots 100 each iteration
# with a concurrency of 20 instances. A total of 1000 instances are
# booted.  These instances are attached to a network which creates
# additional telemetry load.  In between Boot storms, Gnocchi responsiveness
# benchmarks are run to verify responsiveness at scale.  Afterwards, view
# how system resources and api responsiveness degrade over each new set of
# instances booted.
browbeat:
  cloud_name: openstack
  rerun: 10
  rerun_type: complete
  start_stop_collectd: false
  create_grafana_annotations: false
ansible:
  hosts: ansible/hosts
  metadata_playbook: ansible/gather/stockpile.yml
  logging_playbook: ansible/common_logging/browbeat_logging.yml
  start_collectd_playbook: ansible/install/start-collectd.yml
  stop_collectd_playbook: ansible/install/stop-collectd.yml
  check_collectd_config_playbook: ansible/install/check-collectd-config.yml
  ssh_config: ansible/ssh-config
elasticsearch:
  enabled: false
  host: 1.1.1.1
  port: 9200
  life: shortterm
  regather: false
  metadata_files:
    - name: hardware-metadata
      file: metadata/hardware-metadata.json
    - name: environment-metadata
      file: metadata/environment-metadata.json
    - name: software-metadata
      file: metadata/software-metadata.json
    - name: version
      file: metadata/version.json
grafana:
  enabled: true
  host: example.grafana.com
  port: 3000
  dashboards:
    - openstack-general-system-performance
filebeat:
  enabled: false
rally:
  sleep_before: 5
  sleep_after: 5
  plugins:
    - browbeat: rally/rally-plugins/browbeat
    - nova: rally/rally-plugins/nova
    - neutron: rally/rally-plugins/neutron
    - gnocchi: rally/rally-plugins/gnocchi
shaker:
  server: 1.1.1.1
  port: 5555
  flavor: m1.small
  join_timeout: 600
  sleep_before: 0
  sleep_after: 0
  shaker_region: regionOne
  external_host: 2.2.2.2

workloads:

  # Baseline Gnocchi API
  - name: BrowbeatGnocchiResponsiveness
    enabled: true
    type: rally
    concurrency:
      - 8
    times: 5000
    scenarios:
      - name: gnocchi-metric-get-measures-agg-mean-Baseline
        enabled: true
        all_metrics: true
        aggregation: mean
        file: rally/rally-plugins/gnocchi/gnocchi-metric-get-measures.yml
      - name: gnocchi-create-delete-metric-Baseline
        enabled: true
        times: 1000
        file: rally/rally-plugins/gnocchi/gnocchi-create-delete-metric.yml
      - name: gnocchi-create-delete-resource-Baseline
        enabled: true
        times: 1000
        file: rally/rally-plugins/gnocchi/gnocchi-create-delete-resource.yml

  # Boot 100 instances
  - name: BrowbeatNovaPersistWithNetwork
    enabled: true
    type: rally
    concurrency:
      - 20
    times: 100
    scenarios:
      - name: nova-boot-persist-with-network-100
        enabled: true
        image_name: cirro5
        flavor_name: m1.xtiny
        network_start_cidr: 10.1.0.0/23
        cleanup_delay: 1800
        file: rally/rally-plugins/nova/nova_boot_persist_with_network.yml
