---
- hosts: Compute
  remote_user: "heat_admin"
  become: true
  roles:
    - browbeat-metadata/common
    - browbeat-metadata/compute

- hosts: Controller
  remote_user: "heat_admin"
  become: true
  roles:
    - browbeat-metadata/common
    - browbeat-metadata/nova
    - browbeat-metadata/neutron
    - browbeat-metadata/keystone
    - browbeat-metadata/ceilometer
    - browbeat-metadata/gnocchi
    - browbeat-metadata/cinder
    - browbeat-metadata/heat
    - browbeat-metadata/mysql
    - browbeat-metadata/rabbitmq
    - browbeat-metadata/glance

- hosts: Undercloud
  remote_user: "stack"
  become: true
  roles:
    - browbeat-metadata/common
    - browbeat-metadata/undercloud
    - browbeat-metadata/mistral

- name: Dump metadata to files
  hosts: Undercloud
  roles:
    - browbeat-metadata/dump-facts
    - browbeat/oooq-metadata
