---
#
# Browbeat's Shaker Install
#

- name: Create shaker virtualenv
  command: virtualenv {{ shaker_venv }} creates={{ shaker_venv }}
  when: ansible_distribution_major_version <= '8'

- name: Create shaker virtualenv
  command: python3 -m venv {{ shaker_venv }} creates={{ shaker_venv }}
  when: ansible_distribution_major_version == '9'

- name: Setup shaker-venv CA certificate path
  lineinfile:
    dest: "{{ shaker_venv }}/bin/activate"
    line: 'export REQUESTS_CA_BUNDLE={{ overcloud_ca_path }}'
  when: overcloud_ca_path is defined

- name: Install shaker-requirements into shaker-venv
  pip:
    requirements: "{{ browbeat_path }}/tools-requirements.txt"
    virtualenv: "{{ shaker_venv }}"

- name: Install shaker
  pip:
    name: pyshaker
    version: "{{ shaker_version }}"
    virtualenv: "{{ shaker_venv }}"
