- hosts: Undercloud
  remote_user: "{{ local_remote_user }}"
  vars_files:
    - ../install/group_vars/all.yml
  roles:
    - { role: browbeat_logging }

- hosts: Controller
  remote_user: "{{ host_remote_user }}"
  vars_files:
    - ../install/group_vars/all.yml
  roles:
    - { role: browbeat_logging }

- hosts: Compute
  remote_user: "{{ host_remote_user }}"
  vars_files:
    - ../install/group_vars/all.yml
  roles:
    - { role: browbeat_logging }

