- hosts: Undercloud
  remote_user: "{{ local_remote_user }}"
  vars_files:
    - ../install/group_vars/all.yml
  vars:
    config_type: undercloud
  roles:
    - { role: osp_version }
    - { role: filebeat_setup }

- hosts: Controller
  remote_user: "{{ host_remote_user }}"
  vars_files:
    - ../install/group_vars/all.yml
  vars:
    config_type: controller
  roles:
    - { role: osp_version }
    - { role: filebeat_setup }

- hosts: Compute
  remote_user: "{{ host_remote_user }}"
  vars_files:
    - ../install/group_vars/all.yml
  vars:
    config_type: compute
  roles:
    - { role: osp_version }
    - { role: filebeat_setup }

